// We import the font functions from the 'next/font/google' package.
// This is Next.js's built-in way to optimize and load web fonts for the best performance.
import { Geist, Geist_Mono } from "next/font/google";

// We import the global stylesheet. Styles defined in 'globals.css'
// will be applied to the entire application.
import "./globals.css";

// We import the CustomCursor component we created.
// By placing it in the RootLayout, it will be active on every page of the site.
import CustomCursor from "./components/CustomCursor";

// 1. FONT CONFIGURATION
// We initialize the Geist Sans font.
const geistSans = Geist({
  // This tells next/font to set up this font using a CSS variable.
  // This is a modern and flexible way to apply fonts.
  variable: "--font-geist-sans",
  // 'subsets' allows us to load only the characters we need (e.g., Latin characters).
  // This reduces the font file size and improves loading speed.
  subsets: ["latin"],
});

// We do the same for the Geist Mono font.
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. METADATA
// The 'metadata' object allows us to define the page's title and description.
// This is important for SEO (Search Engine Optimization) and for what users see in browser tabs.
export const metadata = {
  title: "Portfolio Templete",
  description: "Customized Portfolio Website",
};

// 3. THE ROOT LAYOUT COMPONENT
// The RootLayout is a special component in Next.js that wraps every page.
// It's used to define the global HTML structure.
// It receives a 'children' prop, which will be the actual page content (e.g., your page.js).
export default function RootLayout({ children }) {
  // The 'return' statement renders the main HTML structure for the entire site.
  return (
    <html lang="en">
      <body
        // We apply the font variables to the body tag. The `${...}` syntax
        // inserts the class names generated by the next/font functions.
        // 'antialiased' is a Tailwind class that smooths out the font for better readability.
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* We render the CustomCursor component here, so it's present on all pages. */}
        <CustomCursor />
        {/* The '{children}' prop is rendered here. This is the placeholder where
            Next.js will inject the content of the current page. */}
        {children}
      </body>
    </html>
  );
}